name:                streams-project
version:             0.1.0.0
github:              "githubuser/streams-project"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/streams-project#readme>

dependencies:
- base >= 4.7 && < 5
- conduit >= 1.3 && < 1.4
- conduit-combinators >= 1.3.0 && < 1.4
- heap >= 1.0.0 && < 1.1.0
- lens >= 4.15.0 && < 4.16.0
- mono-traversable >= 1.0.8 && < 1.0.9
- resourcet >= 1.2.0 && < 1.3.0
- bytestring >= 0.10.8 && < 0.11
- bytestring-conversion >= 0.2 && < 0.3
- parsec >= 3.1 && < 3.2
library:
  source-dirs: src

executables:
  streams-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streams-project

tests:
  streams-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streams-project
